micronaut:
  application:
      name: micronaut_redis_exporter
  server:
    port: 8087

  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
endpoints:
  prometheus:
    sensitive: false

redis:
  uri: redis://host.docker.internal
